@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "admin",
  "email": "u4h56g@example.com",
  "password": "admin123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "u4h5g@example.com",
  "password": "admin123"
}