// Generated by CodiumAI

import { UniqueEntityID } from '@/core/entities/unique-entity-id'
import { AnswerAttachment, AnswerAttachmentProps } from './answer-attachment'

describe('AnswerAttachment', () => {
  // Test that an AnswerAttachment can be created with valid props and id
  it('should create an AnswerAttachment with valid props and id', () => {
    // Arrange
    const answerId = new UniqueEntityID('answerId')
    const attachmentId = new UniqueEntityID('attachmentId')
    const props: AnswerAttachmentProps = {
      answerId,
      attachmentId,
    }
    const id = new UniqueEntityID('id')

    // Act
    const answerAttachment = AnswerAttachment.create(props, id)

    // Assert
    expect(answerAttachment.answerId).toBe(answerId)
    expect(answerAttachment.attachmentId).toBe(attachmentId)
    expect(answerAttachment.id).toBe(id)
  })

  // Test that the answerId and attachmentId can be retrieved correctly from an AnswerAttachment instance
  it('should retrieve answerId and attachmentId when accessing the corresponding properties', () => {
    // Arrange
    const answerId = new UniqueEntityID('answerId')
    const attachmentId = new UniqueEntityID('attachmentId')
    const props: AnswerAttachmentProps = {
      answerId,
      attachmentId,
    }
    const attachment = AnswerAttachment.create(props)

    // Act
    const retrievedAnswerId = attachment.answerId
    const retrievedAttachmentId = attachment.attachmentId

    // Assert
    expect(retrievedAnswerId).toBe(answerId)
    expect(retrievedAttachmentId).toBe(attachmentId)
  })
})
